### ISSUE TITLE
Coveralls가 정상작동 하지 않음

### ISSUE THREAD

**Issue by Choi-Sung-Hoon** [Choi-Sung-Hoon/Django_API#1]
README에서 코드 커버리지를 나타내는 coverage수치가 unknown으로 표기됨.

**Comment by Choi-Sung-Hoon** [comment]
현재 정상 작동하는 것처럼 보이나, Travis CI 터미널에서 확인해보면 여전히 Import Error가 발생하고 있음.

로컬 환경에서 coveralls 실행시 정상 작동함으로써 테스트 결과를 coveralls.io에 제출했지만, Travis CI 환경에서는 작동하지 않음.

```
$ coveralls
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6_with_system_site_packages/bin/coveralls", line 8, in <module>
    sys.exit(wear())
  File "/home/travis/virtualenv/python3.6_with_system_site_packages/lib/python3.6/site-packages/coveralls/__init__.py", line 78, in wear
    from coveralls.control import coveralls
  File "/home/travis/virtualenv/python3.6_with_system_site_packages/lib/python3.6/site-packages/coveralls/control.py", line 2, in <module>
    from coveralls.report import CoverallsReporter
  File "/home/travis/virtualenv/python3.6_with_system_site_packages/lib/python3.6/site-packages/coveralls/report.py", line 6, in <module>
    from coverage.report import Reporter
ImportError: cannot import name 'Reporter'
```
